### ISSUE TITLE
paper has

### ISSUE THREAD

**Issue by henbucuoshanghai** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#10]

**Comment by henbucuoshanghai** [comment]
accepted by ??
the pckh ??when i get the x,y of prediction kps,
how to calculate it with the ground truth x,y  of kps?>???

**Comment by Daniil-Osokin** [comment]
To calculate PCKh there is special function [calc_pckh](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/modules/calc_pckh.py#L100). It expects paths to files with ground truth annotations and predictions in the [LIP dataset](http://sysu-hcp.net/lip/overview.php) format. Basically it is just a `csv` file, where each row contains file name, then keypoints x, y coordinates, separated by comma. Please, see more details in [read_data](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/modules/calc_pckh.py#L5) function.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by henbucuoshanghai** [comment]
you  are very kind .it is very good and useful.
tks
