### ISSUE TITLE
runing this model on arm

### ISSUE THREAD

**Issue by XiaoJiNu** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#11]
Hi, did you test this algrithm on arm platform? What should I do if I want to run it on arm?

**Comment by Daniil-Osokin** [comment]
Hi! We did not test on arm. Actually, it depends on which particular arm you are going to use. If it is a raspberry, I would give a try to OpenCV [dnn](https://www.pyimagesearch.com/2018/09/26/install-opencv-4-on-your-raspberry-pi/) module. If it is a mobile phone, use [PyTorch](https://pytorch.org/mobile/home/) or [TensorFlow Lite](https://www.tensorflow.org/lite/guide/inference) approach. In general, you need to write an app that calls one of inference engine APIs above.

**Comment by XiaoJiNu** [comment]
@Daniil-Osokin thank you very much
