### ISSUE TITLE
Change backbone network,Will it well？

### ISSUE THREAD

**Issue by Willert98** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#13]
Thank for your share ,I noticed that the backbone is mobilenet v1 ,
Have you try change backbone network,Will it well?

**Comment by Willert98** [comment]
emmm,And can you share your work Validation....information ,such as Head  80 .09 Sho 70.0...

**Comment by Daniil-Osokin** [comment]
Hi, we did comparison with MobileNet V2 for the [similar project](https://arxiv.org/pdf/1811.12004.pdf). For some reasons it did not perform well, so we use MobileNet V1 as feature extractor. Mind running [validation](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#validation) to check the numbers or you may look into the [paper](https://arxiv.org/pdf/1906.04104.pdf).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
