### ISSUE TITLE
the inference is too slow 

### ISSUE THREAD

**Issue by duongnv0499** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#15]
Hi, thank for the great work !
I've just tried to infer the model from a single image.
Run on corei7 with no gpu, it product a good result, but it take too long to do (6 seconds per image).  I want to make the model predict from frames of camera video so i need it to run much faster (whereas in paper it said that The network runs at 19.5fps) how can I optimize that to produce at least 10fps ?
thank,

**Comment by duongnv0499** [comment]
one more question, is the model too large ?, i found 40M params for 5 refinement-stages and about 11M for 1 refinement-stages and [this ](https://github.com/opencv/open_model_zoo/blob/master/models/public/single-human-pose-estimation-0001/description/single-human-pose-estimation-0001.md) provide 30M params, all of them are more than paper said. Is that the answer why the inference take too long ?

**Comment by Daniil-Osokin** [comment]
Hi! Actually I did not find any mention of parameters number in the paper for the full network, there is one for the context blocks comparison (p 5.2). The performance numbers in the paper are for 256x256 input image and using OpenVINO as inference framework for CPU. Do you use the same setup?

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
