### ISSUE TITLE
load_state_dict error

### ISSUE THREAD

**Issue by VivienFu** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#17]
File "train.py", line 72, in train
    optimizer.load_state_dict(checkpoint['optimizer'])
  File "/opt/Python3.6/lib/python3.6/site-packages/torch/optim/optimizer.py", line 111, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups

then I change mobilenet_sgd_68.848.pth.tar to Pre-trained model on the Look Into Person dataset (84.57 PCKh@0.5),  this error turn to OK.

what's wrong in mobilenet_sgd_68.848.pth.tar?

**Comment by Daniil-Osokin** [comment]
Hi! Actually everything is ok with `mobilenet_sgd_68.848.pth.tar`. This file contains weights for feature extractor (just a backbone, not the full network) to start training from. It is used in pair with [`load_from_mobilenet`](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/train.py#L65) function to extract weights only for the feature extractor. And pre-trained checkpoint contains weights for pose estimation model as well as states of optimizer and scheduler, see [here](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/train.py#L118).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
