### ISSUE TITLE
Realize the real-time recognition of human body posture by the camera

### ISSUE THREAD

**Issue by congcheng-qu** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#18]
Hello, I am a newcomer to deep learning, and I would like to ask you. If you want to change your program to a camera to dynamically recognize human posture in real time, is there a good way?

**Comment by Daniil-Osokin** [comment]
Hi! This is a single person pose estimation model. It expects as input cropped image with centered person inside. To run the dynamic demo you need to detect persons in a frame (with object detector), then run for each pose estimation model. [Here](https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/single_human_pose_estimation_demo/python) you can find the example of such demo. Or you may consider [this](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) demo, it does multi-person pose estimation at once.

**Comment by congcheng-qu** [comment]
Ok, thank you very much.
