### ISSUE TITLE
Is there the code to train with coco?

### ISSUE THREAD

**Issue by kevkid** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#20]
How can I train with coco? I see there is a pretrained model (where the link does not work) using coco but I do not see anything with coco? Can I use this?: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/datasets/coco.py

**Comment by Daniil-Osokin** [comment]
Hi! Thanks, updated the link in #21. It seems, that COCO training code has been removed from OpenVINO repository, so you can adapt current code accordingly and train the model or use [older state](https://github.com/openvinotoolkit/training_extensions/pull/175) of the OpenVINO repository.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
