### ISSUE TITLE
why the size of model is so large

### ISSUE THREAD

**Issue by VolcanoGao** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#4]
When I train the CPM with 6-stage, it only takes about 120Mb finally. But when I train gccpm, the model of 5 refinement stage is about 400Mb, and even model with 2 stages is still 200Mb. I don't understand why the inference speed can be so fast with so large model. Is it benefit of MobileNet mainly? Thank you very much.

**Comment by VolcanoGao** [comment]
And when I test the speed, I find that it can reach 50fps for the 2-stage refinement, so I'm very confused...Did I do something wrong?

**Comment by Daniil-Osokin** [comment]
Hi, it's the size of the full checkpoint, not the model. Actually `optimizer` state_dict takes a lot of space. Model with 1 stage of refinement is about 44 MB, with 5 is about 150 MB. You can see it if comment out saving `optimizer` state_dict in checkpoint.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
